### ISSUE TITLE
Emo-memo: Fetchte gecikme

### ISSUE THREAD

**Issue by zehraworks** [aydinfz/the-odin-project#2]
Sayfa ilk açıldığında kartlar yüklenirken geç geliyor.

**Comment by sametcodes** [comment]
@aydinfz bunun için Card compenenti için [react-loading-skeleton](https://www.npmjs.com/package/react-loading-skeleton
) kullanabilirsin. Skeleton componentini yönetmek için bir loading state oluşturabilirsin.
